### PR TITLE
Message does not contain guildid when using MessageChannel#sendMessage()

### PR DESCRIPTION
**Pull request by DRSchlaubi**

### CODE REVIEW

**Comment by queer** [comment]
I assume you checked the raw responses from Discord and verified that it's not in there?

**Comment by DRSchlaubi** [comment]
I did

**Comment by queer** [comment]
Thanks for not being @SamOphis ^^

**Comment by SamOphis** [comment]
Hey i test *all* the time





*disclaimer: `all` in this context does not mean `all` in a logical sense samophis is immune to any and all (logical) criticism and discrimination for his lack of Test-Driven-Development*

**Comment by natanbc** [comment]
how about a 2d block this time @queer?

**Pull request merged**
