### PR TITLE
Update Guild Feature Flags

### PR DESCRIPTION
**Pull request by Lulalaby**
See https://github.com/discord/discord-api-docs/pull/3174

### CODE REVIEW

**Comment by queer** [comment]
Thanks!

**Comment by Lulalaby** [comment]
You're welcome
More coming

**Comment by Lulalaby** [comment]
Note:
THREE_DAY_THREAD_ARCHIVE > Premium (Boost) Tier 1
SEVEN_DAY_THREAD_ARCHIVE > Premium (Boost) Tier 2
PRIVATE_THREADS > Premium (Boost) Tier 2

**Comment by queer** [comment]
This should be noted in javadoc comments on the relevant features.

**Comment by Lulalaby** [comment]
I'll do

**Pull request merged**
