### PR TITLE
Test immutables

### PR DESCRIPTION
**Pull request by queer**
THIS DOES NOT COMPILE YET.

Experiments with using immutables.org as a replacement for lombok.

Things to be aware of / fix / consider / etc:

- OkHTTP has been replaced with the new JDK HTTP client
- Audit log entries: `Method 'whatever' cannot have own generic type parameters. Attribute accessors can only use enclosing type's type variables.`
- Switch to following JavaBeans conventions?
- Fix missing JSR305 annotations in the Presence/Embed Builders
- Fix missing JSR305 annotations on generated code so that IJ stops getting upset
- I think I accidentally deleted requester from CatnipOptions?
- Channels need to inject catnip into the override object instances when injecting catnip
- Some ugly copy/pasting, because annoying stuff with immutables...
  - `ApplicationOwner`/`User`, `CreatedInvite`/`Invite`
- `CreatedInvite` is not actually used now, because of compile errors I didn't wanna fix
- Lots of inner interfaces are hoisted up to their own classes
- Generics are abused to hell and back to make immutables generate working code
- this doesn't compile lol

### CODE REVIEW

**Comment by queer** [comment]
cc @natanbc @KJP12

**Comment by natanbc** [comment]
>`I think I accidentally deleted requester from CatnipOptions?` 
:star:

**Comment by queer** [comment]
Some related thoughts:

- I actually like using immutables way more than lombok, overall. Being able to create entities like this is really nice:
  ```Java
  @Modifiable
  @CatnipEntity
  @JsonDeserialize(as = WhateverImpl.class)
  public interface Whatever {}
  ```
- The entity code is a giant tangle that isn't friendly to using immutables as it currently is. The combination of some inheritance + the `RequiresCatnip` interface makes things like JSON de/serializing a complete mess (Hi `CodecTest`!). Pretty much everything in `CodecTest` failed the times I actually got this to compile; switching over would require either heavier abuse of generics than what we already do, or a complete reorganization of the entity inheritance hierarchy. Either one of those really feels like reason to make a 2.x release.
- New HTTP client is :ok_hand: 
- Since the target branch of this PR is about getting rid of vert.x, it probably makes sense to switch to JavaBeans conventions for getters / setters. See #279 
- Crashing `javac` is not fun to debug. At all.

**Comment by KJP12** [comment]
Looks good so far. Although, being able to autogen some parts is a bonus.

Also, how is JSON support looking for Vert.x's JSON, if we are even going to keep Vert.x. If we aren't, what will be replacing it?

**Comment by queer** [comment]
Haven't made it that far yet. This branch still uses vert.x for the websocket / JSON / event loop parts

**Comment by KJP12** [comment]
I will also make sure that my master (since I accidentally pushed fuck-vertx into it) is kept updated to reflect this branch, probably in a branch over. 

Alright. We might as well make sure and go with a JSON library now while we're doing something compatible with JSON.

**Comment by queer** [comment]
Honestly I think the main concern atm is the unbelievable mess that this made of the entity/inheritance tree. Having to split up / hoist classes, making `RequiresCatnip` and `GuildEntity` and I think `GuildChannel` take type parameters, inventing a bunch of new interfaces to avoid code duplication, ... It doesn't feel very nice to work with internally.

**Comment by KJP12** [comment]
Yea, at its current scale, it kinda looks like it will be quite the mess, although viewing from a diff makes it quite messy. Lots of getters that weren't needed before are here now, so... :thinking: Lombok had that nice with just autogenerating those getters but seemed a bit limited with just all or one at a time. It's just a trade-off from switching annotation processors.

**Comment by queer** [comment]
Take `RequiresCatnip` for example. If we don't implement that on a class, we can't inject `Catnip` instances into things. But immutables doesn't (seem to?) work right with how it's declared on master - a type `T` implementing `RequiresCatnip` will be generated with a `T catnip(Catnip catnip)` method, which doesn't correctly implement `RequiresCatnip`. Thus, we end up with a giant chain of generics all the way down through `GuildChannel`/`GuildEntity`/`RequiresCatnip` just to force it to generate methods correctly. This honestly feels like a pretty big step backwards from lombok, at least with how things are in their current form. This leads to horrors like what `Invite`/`CreatedInvite` and `User`/`ApplicationOwner` turned into.

**Comment by queer** [comment]
Actually it's even worse than that, because a type `T` implementing `RequiresCatnip` will have a generated method `TImpl catnip(Catnip catnip)`, meaning that we actually need to be aware of what the generated sources are for the interface declaration! :scream:

**Comment by KJP12** [comment]
*Make our own annotation processor.* /s

Yea, that does make a mess with generics. An issue that seems like that it's hard to avoid. If there is a cleaner solution than tossing generics into it, lets use it.

**Comment by KJP12** [comment]
Thinking about it, how feasible would it be to streamline the entity hierarchy. Of course, we can assume the impl will just be generated by Immutables, so, we could just remove those and be fine. Would streamlining the hierarchy help with the immutable issues?

Oh yea, there is the thing that channels can be updated on the fly, which Immutables may not be helpful in this case. If it will allow us to make special case mutables, then ignore this section. :man_shrugging:

**Comment by queer** [comment]
Immutables lets you make mutable classes - `@Modifiable` vs. `@Immutable`, so I don't think that's much of a concern. The real issue is that I think it'll end up being a giant "rewrite" of the entity hierarchy and everything that it touches (permission checks, convenience methods, etc.)

**Comment by KJP12** [comment]
Yes. If that is going to be a case, we should really take into measures to mostly negate that. Also, we may not need the `asX()` methods, granted inline casting ((X) y).z() isn't as pretty. 

The hierarchy is also potentially going to break stuff, unlike switching out the HTTP client entirely, so, we should watch for that when we do a rewrite of the hierarchy if we have to.

**Pull request closed without merging**
