### PR TITLE
Provide better shard management abstractions

### LINKED ISSUE #85: Better abstractions for custom shard managers
Right now, the DefaultShardManager implementation is heavily dependent on knowing how shards work internally, which isn't ideal. We should provide a friendlier interface to this if at all possible.

### PR DESCRIPTION
**Pull request by queer**
Not ready to merge this, just gonna open it for @natanbc @SamOphis @gabixdev to give feedback on.

Fixes #85

### CODE REVIEW

**Comment by natanbc** [comment]
Maybe add an option to start specific shard ids (from an array/list), or at least a range?

**Comment by queer** [comment]
This is on the list to add

**Comment by queer** [comment]
@natanbc @gabixdev I think this covers everything you guys would want?

**Comment by gabixdev** [comment]
seems 👌

**Comment by queer** [comment]
Okay this is probably good so let's merge it and see what happens :clap:

**Comment by queer** [comment]
Well look at that, it doesn't work :tada:

**Pull request merged**
