### PR TITLE
replaceAtIndex addition + docs for it

### PR DESCRIPTION
**Pull request by SamOphis**
**N O T** tested but the logic is very easy and should definitely work and has been reviewed.
looking for any possible changes, especially to the documentation.

### CODE REVIEW

**Comment by natanbc** [comment]
go test before PRing

**Comment by SamOphis** [comment]
I don't listen to Scala users, thank you.

**Comment by gabixdev** [comment]
ophis gay tbh

**Comment by SamOphis** [comment]
No but on a serious note I submit PR's early so I can get input from other people

**Comment by Stupremee** [comment]
nobody needs testing

**Comment by gabixdev** [comment]
go write unit tests then

**Comment by queer** [comment]
Closes #203

**Pull request merged**
