### PR TITLE
Add basic Rx2 support

### PR DESCRIPTION
**Pull request by queer**
It has been argued that catnip doesn't really count as reactive, and after looking things over, I honestly have to agree with this. This PR is made to make catnip actually properly reactive like it was supposed to be since the beginning. Rx2 is used here because vert.x's support for reactive-streams is terrible it seems :(

This PR would lead to calling catnip a "fully-async, *optionally-reactive*" library.

- [x] Add `Observable`/`Flowable` variant of `Catnip#on` for gateway events

To explore in a future PR:
- Add a proxy or something to wrap REST calls in `Observable` variants
- Make the ratelimiter actually use Rx internally

### CODE REVIEW

**Comment by queer** [comment]
cc @natanbc @gabixdev @KJP12 etc., would like your opinions on this

**Comment by KJP12** [comment]
As long it doesn't break stuff, should be alright to work with.

**Comment by queer** [comment]
Honestly, given how difficult it would be for the REST/ratelimiter things to be ported at this point in time, I'll just merge this as-is and we can explore converting those in a future PR.

**Comment by gabixdev** [comment]
I'd rather keep it as an add-on, I don't really like having unused dependencies :/

**Pull request merged**
