### PR TITLE
catnip v2

### PR DESCRIPTION
**Pull request by queer**
Full of breaking changes, ofc.

- `Catnip#observable` and `Catnip#flowable` are first-class now
- `Catnip#on` is still exposed for those who want it
- Pulls in the `fuck-vertx` branch for the websocket / HTTP changes
- Converts all REST methods to using Observable/Completable/Single
- Converts cache methods to using Single
- Replacing vert.x for event loops
- #227
- Real timer task alternative
- Replacing verticles
- Give shards a real event bus for dispatching events to Rx subscribers
- Real non-vx JSON lib

To consider/do:
- Convert ratelimiters to use Flowable because backpressured streams are nice
- Convert CacheViews to use Single/Observable/...
- Convert pagination classes to use Flowables

### CODE REVIEW

**Comment by queer** [comment]
Thinking about it more, it would probably make more sense if we were to convert CacheViews to solely use Observable/Single/... internally

**Comment by queer** [comment]
*as the interface, not just internally

**Comment by queer** [comment]
Should also make the pagination-related classes use Flowables internally, I think

**Comment by queer** [comment]
@KJP12 @natanbc @gabixdev @SamOphis I'm summoning you for another discussion because I want your opinions on how to do this in a less-painful manner. 

So since we're removing vert.x, the two Big Problems:tm: left are fully replacing vert.x's event bus (since annoyingly we're still using it underneath the Rx stuff, see [this](https://github.com/mewna/catnip/blob/86c8b7c7fa78c9b1d9bb398d7a80cf0c94431d42/src/main/java/com/mewna/catnip/Catnip.java#L703-L809)), and properly replacing verticles, because 1) extensions use them, and more importantly 2) shards use them.

The main thing with the latter Problem:tm: is basically just that we do the sorta-message-passing-ish thing to control shards, and as we already know, it can be pretty fragile at times. The obvious solution here is just to make the shard manager a glorified queue (more so than it already is) and just append shard instances to the end of the queue whenever necessary. My concern there is that iirc we're already treating shard instances as "just blow away the entire thing and push out a new one," and so I'd just wanna be sure that we're actually handling that correctly. 

Beyond that, I'm pretty sure it'll involve a pretty substantial refactoring of shard logic to take all the stuff that's done in a message-passing-y way (sending websocket messages, shard control like dis/connect, ...) and that's not gonna be very pleasant, I think...

**Comment by SamOphis** [comment]
- event bus is quite easy to replace properly, especially since it's not entirely necessary to convert objects to json and back, and we get to get rid of codec memes
- we can always use a different actor model (similar to Akka for example) to replace verticles, or just rewrite the shard class altogether and get rid of the sometimes-weird message passing, or just use standard objects and callback methods (this is the approach i favour)

overall i welcome most of these changes since vert.x is just a disappointment at this point. i also don't really like the "queue and ditch" approach with shards and shardmanagers, since the name implies the manager will manage shards until they die. not just that, i prefer being able to access the shard directly instead of just queuing and leaving it to do its own stuff

**Comment by queer** [comment]
Main concern with the event bus aspect is just that I haven't checked to be certain how the JDK websocket client actually works wrt. threads (is it on the calling thread? its own thread? ...), and as such I don't want to just make a generic potentially-blocking event bus that screws up the WS client's operation. @KJP12 might know?

**Comment by adriantodt** [comment]
@queer I am using JDK11 WebSockets and I have an example implementation:
https://github.com/arudiscord/andeclient/blob/master/src/main/java/pw/aru/libs/andeclient/internal/NodeWebSocket.java

For some reason, you have to put a ReentrantLock or a Semaphore on sending frames, or packets might not be sent because of some race condition.

**Comment by queer** [comment]
@SamOphis 
> not just that, i prefer being able to access the shard directly instead of just queuing and leaving it to do its own stuff
One of the points we were getting at with the design is that you *should never need to access the shard object directly.* The thinking was basically "If the API that we have doesn't let you do something, then that's something we should fix, rather than expose the shard object publicly." The only case I can see direct shard object access being necessarily useful is in the case of wanting to reflectively access its internals, which imo should be heavily discouraged.

**Comment by queer** [comment]
Should replace vert.x timers/intervals with Observable#timer/interval(), and also probably(?) expose a utility method somewhere to use for those.

**Comment by queer** [comment]
Previous comment is finished but untested as of 3faeda9b1983f03ba6a8dd035ee7745e463496ff.

**Pull request merged**
