### PR TITLE
Made 'EntityBuilder' non-final

### LINKED ISSUE #314: Dumb feature idea: Let users plug in custom EntityBuilders
Questions:
- What kind of interface would `EntityBuilder` have?
- How to "inject" it?
- Do we mess with method signatures (ie. `List<Role> roles()` -> `<T extends Role> List<T> roles()` sort of thing) to avoid a lot of casting?
- Should the default `EntityBuilder` be non-`final` to allow for users to extend it to have a non-terrible time of implementing?

### PR DESCRIPTION
**Pull request by Stupremee**
Resolves #314

### CODE REVIEW

**Comment by queer** [comment]
@Stupremee ping, it's been a month so just wanna check what's going on here

**Comment by Stupremee** [comment]
I will try to do it in the next days.
I had an idea how to implement custom entites.
Every method that returns a User or any other entity takes a Class as parameter and will return the type of the class. 
When you create a new Catnip instance, you can inject entity builders for different classes.
e.g.
```java
public class SpecialUser {
    private final User user;
    private final int coins;

    public SpecialUser(User user, int coins) {
        this.user = user;
        this.coins = coins;
    }

    // Accessor...
}

public class SpecialUserBuilder implements CustomEntityBuilder<SpecialUser> {
    private Catnip catnip;

    @Override
    public SpecialUser build(JsonObject raw) {
        User standardUser = this.catnip.entityBuilderRegistry().forClass(User.class).build(raw);
        SpecialUser specialUser = new SpecialUser(standardUser, getCoinsForUser(standardUser));
    }

    @Override
    public void catnip(Catnip catnip) {
        this.catnip = catnip;
    }
}

// I never really used catnip in production so probably this wont compile
// The method will try to find a builder for the given class and then use the builder to build the SpecialUser. If no builder was found, just throw an exception
SpecialUser user = catnip.rest().user().getUser("123", SpecialUser.class);
System.out.println(user.coins());
```
You can do the same with Guilds, Channels etc

**Comment by queer** [comment]
Yeah I'm not sure if something like that would be best; a simple `Whatever extends EntityBuilder` is probably for the best.

**Comment by Stupremee** [comment]
But how can a user then control which entity type is returned by a method?

**Comment by natanbc** [comment]
```java
public class MyBuilder extends EntityBuilder {
    @Override
    public User createUser(JsonObject payload) {
        return new MyUserClass(...);
    }
}
```

```java
MyUserClass user = (MyUserClass) catnip().rest().user().getUser("123").join();
```

**Comment by queer** [comment]
Pretty much what Natan said. The easiest way to deal with it is to just make people who are smart enough to use this cast everything themselves, since they would know that they want to do that.

**Comment by Stupremee** [comment]
Okay I will try to implement it in the next few days

**Pull request closed without merging**
